services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskflow
    volumes:
      - ./server:/app
      - /app/node_modules   # Prevent overwriting node_modules in container
    depends_on:
      - mongo
    restart: always

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules   # Prevent overwriting node_modules in container
    depends_on:
      - server
    restart: always

volumes:
  mongo-data:
