services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: jenkins_server
    ports:
      - "6000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskflow
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: jenkins_client
    ports:
      - "6173:5173"
    volumes:
      - ./client:/app
    depends_on:
      - server

volumes:
  mongo-data:
